// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformService.Platform.Data;

#nullable disable

namespace PlatformService.Platform.Data.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlatformService.Platform.Models.PlatformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 85m,
                            Name = "Tasty Steel Gloves",
                            Publisher = "Daniel Inc"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 11m,
                            Name = "Awesome Granite Car",
                            Publisher = "Langworth - Goodwin"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 30m,
                            Name = "Licensed Rubber Table",
                            Publisher = "Herman Inc"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 56m,
                            Name = "Handcrafted Soft Keyboard",
                            Publisher = "Hahn - Gerlach"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 98m,
                            Name = "Sleek Granite Chicken",
                            Publisher = "Hegmann - Dickinson"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 45m,
                            Name = "Intelligent Granite Table",
                            Publisher = "Powlowski and Sons"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 43m,
                            Name = "Unbranded Steel Table",
                            Publisher = "Murray LLC"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 5m,
                            Name = "Handcrafted Metal Chicken",
                            Publisher = "Koelpin, Bogan and Wiegand"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 59m,
                            Name = "Small Granite Sausages",
                            Publisher = "Haley, Kerluke and Rosenbaum"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 8m,
                            Name = "Generic Steel Car",
                            Publisher = "Conn, Pagac and Heidenreich"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 53m,
                            Name = "Tasty Frozen Chair",
                            Publisher = "Bruen, Johnson and Murazik"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 59m,
                            Name = "Sleek Wooden Pizza",
                            Publisher = "Lubowitz LLC"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 60m,
                            Name = "Incredible Fresh Chips",
                            Publisher = "Lueilwitz - Beatty"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 6m,
                            Name = "Sleek Cotton Salad",
                            Publisher = "Gleason, Mayert and Hahn"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 68m,
                            Name = "Handmade Steel Gloves",
                            Publisher = "Frami - Johnston"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 60m,
                            Name = "Intelligent Steel Chair",
                            Publisher = "Reinger Group"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 77m,
                            Name = "Handcrafted Plastic Soap",
                            Publisher = "Krajcik - Blick"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 17m,
                            Name = "Tasty Wooden Car",
                            Publisher = "Willms, Rosenbaum and Bruen"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 62m,
                            Name = "Tasty Plastic Fish",
                            Publisher = "Howell Group"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 90m,
                            Name = "Practical Granite Pants",
                            Publisher = "Boyle, Lebsack and Block"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 31m,
                            Name = "Handmade Fresh Table",
                            Publisher = "Kub, Leannon and Turcotte"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 40m,
                            Name = "Handcrafted Cotton Shirt",
                            Publisher = "Ratke - Schuppe"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 6m,
                            Name = "Fantastic Frozen Bacon",
                            Publisher = "Hirthe - Kiehn"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 70m,
                            Name = "Intelligent Cotton Mouse",
                            Publisher = "Hettinger, Ledner and Wilderman"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 20m,
                            Name = "Handcrafted Soft Computer",
                            Publisher = "Oberbrunner and Sons"
                        },
                        new
                        {
                            Id = 26,
                            Cost = 39m,
                            Name = "Licensed Rubber Soap",
                            Publisher = "Zboncak Inc"
                        },
                        new
                        {
                            Id = 27,
                            Cost = 34m,
                            Name = "Handmade Frozen Towels",
                            Publisher = "Mayert, Wilkinson and Keeling"
                        },
                        new
                        {
                            Id = 28,
                            Cost = 72m,
                            Name = "Small Soft Computer",
                            Publisher = "Greenfelder Inc"
                        },
                        new
                        {
                            Id = 29,
                            Cost = 41m,
                            Name = "Gorgeous Frozen Towels",
                            Publisher = "Rutherford - Heaney"
                        },
                        new
                        {
                            Id = 30,
                            Cost = 72m,
                            Name = "Sleek Soft Cheese",
                            Publisher = "Gulgowski - O'Kon"
                        },
                        new
                        {
                            Id = 31,
                            Cost = 70m,
                            Name = "Practical Frozen Shirt",
                            Publisher = "Davis Group"
                        },
                        new
                        {
                            Id = 32,
                            Cost = 84m,
                            Name = "Rustic Rubber Mouse",
                            Publisher = "Brakus LLC"
                        },
                        new
                        {
                            Id = 33,
                            Cost = 59m,
                            Name = "Small Soft Car",
                            Publisher = "Kiehn - Bradtke"
                        },
                        new
                        {
                            Id = 34,
                            Cost = 18m,
                            Name = "Unbranded Rubber Cheese",
                            Publisher = "Mraz - Wolff"
                        },
                        new
                        {
                            Id = 35,
                            Cost = 97m,
                            Name = "Unbranded Metal Chicken",
                            Publisher = "Skiles and Sons"
                        },
                        new
                        {
                            Id = 36,
                            Cost = 93m,
                            Name = "Ergonomic Cotton Fish",
                            Publisher = "Friesen - Watsica"
                        },
                        new
                        {
                            Id = 37,
                            Cost = 100m,
                            Name = "Handcrafted Rubber Keyboard",
                            Publisher = "Nader Group"
                        },
                        new
                        {
                            Id = 38,
                            Cost = 94m,
                            Name = "Generic Concrete Hat",
                            Publisher = "Beatty Inc"
                        },
                        new
                        {
                            Id = 39,
                            Cost = 37m,
                            Name = "Unbranded Concrete Chair",
                            Publisher = "Connelly Inc"
                        },
                        new
                        {
                            Id = 40,
                            Cost = 1m,
                            Name = "Tasty Rubber Salad",
                            Publisher = "Rempel Group"
                        },
                        new
                        {
                            Id = 41,
                            Cost = 42m,
                            Name = "Small Soft Keyboard",
                            Publisher = "Mraz Inc"
                        },
                        new
                        {
                            Id = 42,
                            Cost = 16m,
                            Name = "Handmade Rubber Ball",
                            Publisher = "Larkin, Tromp and Deckow"
                        },
                        new
                        {
                            Id = 43,
                            Cost = 11m,
                            Name = "Gorgeous Concrete Soap",
                            Publisher = "Ernser - Prosacco"
                        },
                        new
                        {
                            Id = 44,
                            Cost = 89m,
                            Name = "Intelligent Frozen Computer",
                            Publisher = "Stark Group"
                        },
                        new
                        {
                            Id = 45,
                            Cost = 11m,
                            Name = "Refined Cotton Shoes",
                            Publisher = "Block and Sons"
                        },
                        new
                        {
                            Id = 46,
                            Cost = 79m,
                            Name = "Unbranded Plastic Soap",
                            Publisher = "Gaylord - Wehner"
                        },
                        new
                        {
                            Id = 47,
                            Cost = 62m,
                            Name = "Handmade Metal Bacon",
                            Publisher = "Glover Group"
                        },
                        new
                        {
                            Id = 48,
                            Cost = 46m,
                            Name = "Rustic Frozen Ball",
                            Publisher = "Bradtke - Kuvalis"
                        },
                        new
                        {
                            Id = 49,
                            Cost = 76m,
                            Name = "Fantastic Plastic Bacon",
                            Publisher = "Daniel - Purdy"
                        },
                        new
                        {
                            Id = 50,
                            Cost = 92m,
                            Name = "Sleek Plastic Bacon",
                            Publisher = "Rogahn and Sons"
                        },
                        new
                        {
                            Id = 51,
                            Cost = 7m,
                            Name = "Tasty Cotton Mouse",
                            Publisher = "DuBuque and Sons"
                        },
                        new
                        {
                            Id = 52,
                            Cost = 23m,
                            Name = "Rustic Cotton Table",
                            Publisher = "Schiller - Spencer"
                        },
                        new
                        {
                            Id = 53,
                            Cost = 78m,
                            Name = "Rustic Granite Bike",
                            Publisher = "Greenholt, Berge and Schuppe"
                        },
                        new
                        {
                            Id = 54,
                            Cost = 37m,
                            Name = "Gorgeous Cotton Gloves",
                            Publisher = "Howell, Bednar and Roberts"
                        },
                        new
                        {
                            Id = 55,
                            Cost = 14m,
                            Name = "Practical Fresh Hat",
                            Publisher = "Stark, Lubowitz and Flatley"
                        },
                        new
                        {
                            Id = 56,
                            Cost = 90m,
                            Name = "Refined Fresh Pants",
                            Publisher = "Murazik LLC"
                        },
                        new
                        {
                            Id = 57,
                            Cost = 97m,
                            Name = "Fantastic Plastic Fish",
                            Publisher = "Schneider Group"
                        },
                        new
                        {
                            Id = 58,
                            Cost = 43m,
                            Name = "Incredible Frozen Towels",
                            Publisher = "Corkery, Quigley and Parisian"
                        },
                        new
                        {
                            Id = 59,
                            Cost = 63m,
                            Name = "Refined Metal Salad",
                            Publisher = "Heidenreich - Feest"
                        },
                        new
                        {
                            Id = 60,
                            Cost = 78m,
                            Name = "Ergonomic Steel Ball",
                            Publisher = "Collins Inc"
                        },
                        new
                        {
                            Id = 61,
                            Cost = 15m,
                            Name = "Handcrafted Wooden Tuna",
                            Publisher = "Weimann Group"
                        },
                        new
                        {
                            Id = 62,
                            Cost = 38m,
                            Name = "Handcrafted Concrete Tuna",
                            Publisher = "Upton - Lynch"
                        },
                        new
                        {
                            Id = 63,
                            Cost = 15m,
                            Name = "Gorgeous Metal Hat",
                            Publisher = "Klein Inc"
                        },
                        new
                        {
                            Id = 64,
                            Cost = 13m,
                            Name = "Rustic Wooden Towels",
                            Publisher = "Vandervort, Bruen and Koepp"
                        },
                        new
                        {
                            Id = 65,
                            Cost = 23m,
                            Name = "Tasty Granite Towels",
                            Publisher = "Pagac Inc"
                        },
                        new
                        {
                            Id = 66,
                            Cost = 37m,
                            Name = "Tasty Plastic Ball",
                            Publisher = "Lynch, Bradtke and O'Reilly"
                        },
                        new
                        {
                            Id = 67,
                            Cost = 22m,
                            Name = "Handmade Wooden Table",
                            Publisher = "Larkin, Krajcik and Kling"
                        },
                        new
                        {
                            Id = 68,
                            Cost = 60m,
                            Name = "Handmade Granite Hat",
                            Publisher = "Johnston Group"
                        },
                        new
                        {
                            Id = 69,
                            Cost = 90m,
                            Name = "Handcrafted Plastic Ball",
                            Publisher = "Cormier Group"
                        },
                        new
                        {
                            Id = 70,
                            Cost = 98m,
                            Name = "Rustic Granite Cheese",
                            Publisher = "Farrell, Johnson and Dach"
                        },
                        new
                        {
                            Id = 71,
                            Cost = 67m,
                            Name = "Refined Concrete Pizza",
                            Publisher = "Grimes and Sons"
                        },
                        new
                        {
                            Id = 72,
                            Cost = 86m,
                            Name = "Awesome Soft Fish",
                            Publisher = "Schiller - Harris"
                        },
                        new
                        {
                            Id = 73,
                            Cost = 95m,
                            Name = "Rustic Soft Bacon",
                            Publisher = "Raynor, Waters and Kutch"
                        },
                        new
                        {
                            Id = 74,
                            Cost = 46m,
                            Name = "Tasty Plastic Sausages",
                            Publisher = "Maggio - Schinner"
                        },
                        new
                        {
                            Id = 75,
                            Cost = 56m,
                            Name = "Intelligent Metal Gloves",
                            Publisher = "MacGyver - Moore"
                        },
                        new
                        {
                            Id = 76,
                            Cost = 9m,
                            Name = "Incredible Plastic Chips",
                            Publisher = "Wolf Group"
                        },
                        new
                        {
                            Id = 77,
                            Cost = 93m,
                            Name = "Incredible Soft Salad",
                            Publisher = "Mraz Group"
                        },
                        new
                        {
                            Id = 78,
                            Cost = 93m,
                            Name = "Unbranded Steel Bike",
                            Publisher = "Gulgowski - Bradtke"
                        },
                        new
                        {
                            Id = 79,
                            Cost = 97m,
                            Name = "Practical Fresh Hat",
                            Publisher = "McKenzie, Waters and Hegmann"
                        },
                        new
                        {
                            Id = 80,
                            Cost = 49m,
                            Name = "Small Steel Shirt",
                            Publisher = "Frami, Carter and Heathcote"
                        },
                        new
                        {
                            Id = 81,
                            Cost = 54m,
                            Name = "Gorgeous Frozen Bike",
                            Publisher = "Abbott - Jakubowski"
                        },
                        new
                        {
                            Id = 82,
                            Cost = 46m,
                            Name = "Practical Soft Tuna",
                            Publisher = "Dickinson - Kris"
                        },
                        new
                        {
                            Id = 83,
                            Cost = 71m,
                            Name = "Handmade Steel Keyboard",
                            Publisher = "Funk - Gerlach"
                        },
                        new
                        {
                            Id = 84,
                            Cost = 64m,
                            Name = "Fantastic Metal Bacon",
                            Publisher = "Gutmann - O'Connell"
                        },
                        new
                        {
                            Id = 85,
                            Cost = 84m,
                            Name = "Fantastic Rubber Bacon",
                            Publisher = "Walsh LLC"
                        },
                        new
                        {
                            Id = 86,
                            Cost = 26m,
                            Name = "Awesome Plastic Car",
                            Publisher = "Purdy Inc"
                        },
                        new
                        {
                            Id = 87,
                            Cost = 49m,
                            Name = "Small Metal Shoes",
                            Publisher = "Roob, Ledner and Towne"
                        },
                        new
                        {
                            Id = 88,
                            Cost = 37m,
                            Name = "Generic Frozen Fish",
                            Publisher = "Williamson and Sons"
                        },
                        new
                        {
                            Id = 89,
                            Cost = 89m,
                            Name = "Generic Concrete Towels",
                            Publisher = "Spencer, Zemlak and Zemlak"
                        },
                        new
                        {
                            Id = 90,
                            Cost = 5m,
                            Name = "Rustic Cotton Chicken",
                            Publisher = "Mohr - McGlynn"
                        },
                        new
                        {
                            Id = 91,
                            Cost = 74m,
                            Name = "Generic Frozen Ball",
                            Publisher = "Stiedemann, Lang and Towne"
                        },
                        new
                        {
                            Id = 92,
                            Cost = 6m,
                            Name = "Unbranded Wooden Cheese",
                            Publisher = "Gibson - O'Hara"
                        },
                        new
                        {
                            Id = 93,
                            Cost = 81m,
                            Name = "Unbranded Frozen Hat",
                            Publisher = "Graham, Roberts and Weimann"
                        },
                        new
                        {
                            Id = 94,
                            Cost = 57m,
                            Name = "Handcrafted Plastic Sausages",
                            Publisher = "Cummings - Stokes"
                        },
                        new
                        {
                            Id = 95,
                            Cost = 87m,
                            Name = "Generic Cotton Car",
                            Publisher = "Rath, Hauck and Schroeder"
                        },
                        new
                        {
                            Id = 96,
                            Cost = 34m,
                            Name = "Fantastic Rubber Shirt",
                            Publisher = "Jacobs and Sons"
                        },
                        new
                        {
                            Id = 97,
                            Cost = 30m,
                            Name = "Handcrafted Rubber Table",
                            Publisher = "Heller, Marks and Hagenes"
                        },
                        new
                        {
                            Id = 98,
                            Cost = 62m,
                            Name = "Rustic Concrete Bacon",
                            Publisher = "Bogan, Jones and Schultz"
                        },
                        new
                        {
                            Id = 99,
                            Cost = 81m,
                            Name = "Licensed Fresh Pizza",
                            Publisher = "Bradtke - Barton"
                        },
                        new
                        {
                            Id = 100,
                            Cost = 34m,
                            Name = "Refined Cotton Towels",
                            Publisher = "Hills - Adams"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
